import './services.scss'
const Services = () => {
  return (
    <div className='services'>
        <div className="text-container">
            <p>
                  I foucs on helping your brand grow
                  <br/> and move forward
            </p>
        </div>
        <div className="title-container"></div>
        <div className="list-container"></div>
    </div>
  )
}

export default Services